#BSUB -J manifest
#BSUB -W 24:00
#BSUB -o /rsrch5/home/epi/bhattacharya_lab/users/whwu1/log
#BSUB -e /rsrch5/home/epi/bhattacharya_lab/users/whwu1/log
#BSUB -q medium 
#BSUB -n 2
#BSUB -M 100
#BSUB -R rusage[mem=200]
#BSUB -N
#BSUB -B
#BSUB -u whwu1@mdanderson.org

### LOAD UP MODULES
module load R/4.3.1

### RUN LINES OF CODE
R 
Rscript /rsrch5/home/epi/bhattacharya_lab/users/whwu1/scripts/scripts/pfas_analysis.R
