library(DESeq2)
library(tximeta)
library(RUVSeq)
library(MASS)
library(dplyr)

load("/rsrch5/home/epi/bhattacharya_lab/users/whwu1/out/salmon_data_concise.RData")
cord_pfas_diff <- DESeqDataSetFromMatrix(countData = normalized_counts, colData = pfas_w1, design = ~ W_1 + condition.sex + condition.mother_ethnicity + condition.GROUP + condition.GA + cord_PFBA)
mat_pfas_diff <- DESeqDataSetFromMatrix(countData = normalized_counts, colData = pfas_w1, design = ~ W_1 + condition.sex + condition.mother_ethnicity + condition.GROUP + condition.GA + mat_PFBA)
dds_cord_pfas <- DESeq(cord_pfas_diff)
dds_mat_pfas <- DESeq(mat_pfas_diff)
res_cord_pfas <- results(cord_pfas_diff)
res_mat_pfas <- results(mat_pfas_diff)
save(res_cord_pfas, res_mat_pfas, file = "pfas_results.RData")
