#BSUB -J Star_alignment
#BSUB -W 24:00
#BSUB -o /rsrch5/home/epi/bhattacharya_lab/users/whwu1
#BSUB -e /rsrch5/home/epi/bhattacharya_lab/users/whwu1
#BSUB -q medium 
#BSUB -n 1
#BSUB -M 100
#BSUB -R rusage[mem=100]
#BSUB -N
#BSUB -B
#BSUB -u whwu1@mdanderson.org
### LOAD UP MODULES
module add star
eval "$(/risapps/rhel8/miniconda3/py39_4.12.0/bin/conda shell.bash hook)"
            conda activate star-2.7.10b
### DEFINE GLOBAL VARIABLES
fasta_file="/rsrch5/home/epi/bhattacharya_lab/data/GenomicReferences/genome/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
gtf_file="/rsrch5/home/epi/bhattacharya_lab/data/GenomicReferences/txome/gencode_v45/gencode.v45.annotation.nochr.gtf"
star_database_v45_grch38="/rsrch5/home/epi/bhattacharya_lab/data/GenomicReferences/star_database_v45_grch38"
out_folder_alignment="/rsrch5/home/epi/bhattacharya_lab/users/whwu1/out_folder_alignment"
file1="/rsrch5/home/epi/bhattacharya_lab/users/whwu1/out_J1001_1_trimmed.fastq"
file2="/rsrch5/home/epi/bhattacharya_lab/users/whwu1/out_J1001_2_trimmed.fastq"
### RUN LINES OF CODE
STAR --genomeDir "$star_database_v45_grch38" --readFilesIn "$file1" "$file2"  --outFileNamePrefix "$out_folder_alignment"/J1001_ --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 5 --outFilterMultimapNmax 1 --runThreadN 4
### CLEANUP
