library(tximeta)
subdirs <- list.dirs("/rsrch5/home/epi/bhattacharya_lab/data/mapqtl/GUSTO/salmon_output", recursive = FALSE)
files <- file.path(subdirs, "quant.sf")
sample_id <- paste0("J", 1001:1200)
coldata <- data.frame(files, names = sample_id, stringsAsFactors=FALSE)
se <- tximeta(coldata)
save.image("salmon_data.RData")
