#BSUB -J manifest
#BSUB -W 24:00
#BSUB -o /rsrch5/home/epi/bhattacharya_lab/users/whwu1/log
#BSUB -e /rsrch5/home/epi/bhattacharya_lab/users/whwu1/log
#BSUB -q medium 
#BSUB -n 1
#BSUB -M 50
#BSUB -R rusage[mem=50]
#BSUB -N
#BSUB -B
#BSUB -u whwu1@mdanderson.org

### LOAD UP MODULES
module load R/4.1.0

### Directories
salmon_output=/rsrch5/home/epi/bhattacharya_lab/data/mapqtl/GUSTO/salmon_output

### RUN LINES OF CODE
R --save
library(tximeta)
subdirs <- list.dirs("$salmon_output", recursive = FALSE)
quant_files <- file.path(subdirs, "quant.sf")
sample_id <- paste0("J", 1001:1200)
coldata <- data.frame(quant_files, names = sample_id, stringsAsFactors=FALSE)
se <- tximeta(coldata)
save.image(file = "salmon_dataset.RData")
