#BSUB -J manifest
#BSUB -W 24:00
#BSUB -o /rsrch5/home/epi/bhattacharya_lab/users/whwu1/log
#BSUB -e /rsrch5/home/epi/bhattacharya_lab/users/whwu1/log
#BSUB -q medium 
#BSUB -n 1
#BSUB -M 50
#BSUB -R rusage[mem=50]
#BSUB -N
#BSUB -B
#BSUB -u whwu1@mdanderson.org

### LOAD UP MODULES
module load R/4.1.0

### RUN LINES OF CODE

R --save
Rscript /rsrch5/home/epi/bhattacharya_lab/users/whwu1/scripts/scripts/tximeta.R
